### ISSUE TITLE
gulpfile syntax error

### ISSUE THREAD

**Issue by newbieh4cker** [ericyd/gdrive-copy#118]
### Are you requesting a feature or reporting a bug?
reporting bug

### If reporting a bug, is there already an issue open for this same bug?
not likely

### What is the current behavior?
while "clasp push"
-> \ Pushing files...Push failed. Errors:
{ Error: Syntax error: Missing ; before statement. line: 64 file: gulpfile
    at Gaxios.request (/usr/local/lib/node_modules/@google/clasp/node_modules/gaxios/build/src/gaxios.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

### What is the expected behavior?
no error

### Specify your

* operating system: macOS Mojave(10.14.6) / node v8.11.4
* browser: Chrome

**Comment by newbieh4cker** [comment]
OS : macOS Mojave(10.14.6)
Node : v8.11.4
npm : 5.6.0

1. git clone https://github.com/ericyd/gdrive-copy/
![image](https://user-images.githubusercontent.com/23703741/63731628-75a19f80-c8ab-11e9-99f0-b978ef9d695d.png)

2. cd gdrive-copy && npm i
![image](https://user-images.githubusercontent.com/23703741/63731616-6cb0ce00-c8ab-11e9-8182-323e7c58bec3.png)

3. npm i -g @google/clasp 
![image](https://user-images.githubusercontent.com/23703741/63731644-894d0600-c8ab-11e9-9646-447c60076ded.png)

4. clasp create --type webapp
![image](https://user-images.githubusercontent.com/23703741/63731681-b699b400-c8ab-11e9-842b-ddae773b7f78.png)

5. clasp login
![image](https://user-images.githubusercontent.com/23703741/63731737-f2cd1480-c8ab-11e9-862e-3c769cf92c8b.png)

6. changed 'MAX_RUNTIME_PER_DAY" in lib/Timer.ts from 88 to 355
* I'm going to use my own g-suite business account

7. npm run build:prod  
> https://pastebin.com/EvXYNiYe

8. clasp push
> https://pastebin.com/j4pXFxPR

**Comment by newbieh4cker** [comment]
@ericyd 

okay, solved gulpfile issuse
i was using my old script id.
sorry for that.
