### ISSUE TITLE
Failure to build

### ISSUE THREAD

**Issue by sbwoodside** [ericyd/gdrive-copy#143]
Building from scratch, I get the error:

Here is the complete log:

```
simonwoodside@Simons-Work-MBP sandbox % git clone git@github.com:ericyd/gdrive-copy.git
Cloning into 'gdrive-copy'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 4445 (delta 37), reused 35 (delta 18), pack-reused 4372
Receiving objects: 100% (4445/4445), 3.41 MiB | 4.83 MiB/s, done.
Resolving deltas: 100% (2900/2900), done.
simonwoodside@Simons-Work-MBP sandbox % cd gdrive-copy && npm i


> fsevents@1.1.3 install /Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v79-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@13.6.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v79-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@13.6.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.


No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.


gyp: No Xcode or CLT version detected!
gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp gypERR!  configure error 
ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR!gyp System  Darwin 19.2.0
gypERR! ERR!  command "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64"
stackgyp Error: `gyp` failed with exit code: 1
 ERR!gyp  cwdERR! /Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents
 gypstack      at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
ERR!gyp node -v  v13.6.0
gypERR! ERR!  stacknode-gyp -v     at ChildProcess.emit (events.js:321:20)
 v5.0.5
gypgyp  ERR!ERR!  stacknot ok 
     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64"
gyp ERR! cwd /Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.6.0/bin/node" "/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents
node-pre-gyp ERR! node -v v13.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/simonwoodside/sandbox/gdrive-copy/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64' (1)

> phantomjs-prebuilt@2.1.16 install /Users/simonwoodside/sandbox/gdrive-copy/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/3q/wh5g17t50dz02dzb3gkvh15h0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/simonwoodside/sandbox/gdrive-copy/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/3q/wh5g17t50dz02dzb3gkvh15h0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1578973557918/phantomjs-2.1.1-macosx -> /Users/simonwoodside/sandbox/gdrive-copy/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/simonwoodside/sandbox/gdrive-copy/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> sinon@4.5.0 postinstall /Users/simonwoodside/sandbox/gdrive-copy/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1669 packages from 1312 contributors and audited 7807 packages in 20.125s
found 602 vulnerabilities (169 low, 31 moderate, 399 high, 3 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
simonwoodside@Simons-Work-MBP gdrive-copy % npm i -g @google/clasp 
/usr/local/bin/clasp -> /usr/local/lib/node_modules/@google/clasp/src/index.js
npm WARN inquirer-autocomplete-prompt@1.0.1 requires a peer of inquirer@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @google/clasp@2.3.0
updated 1 package in 5.932s
simonwoodside@Simons-Work-MBP gdrive-copy % npm run build:prod

> google-drive-copy-folder@6.1.0 build:prod /Users/simonwoodside/sandbox/gdrive-copy
> npm run webpack:prod && npm run gulp:prod && npm run copylib


> google-drive-copy-folder@6.1.0 webpack:prod /Users/simonwoodside/sandbox/gdrive-copy
> webpack --config ./config/webpack.config.prod.js

Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
Hash: f9fde7dfd9e21a391d47
Version: webpack 2.7.0
Time: 6704ms
    Asset     Size  Chunks                    Chunk Names
bundle.js   586 kB       0  [emitted]  [big]  index
 css.html  5.44 kB       0  [emitted]         index
   [0] ./~/react/index.js 190 bytes {0} [built]
  [14] ./~/react-dom/index.js 1.36 kB {0} [built]
  [35] ./src/util/picker.js 3.22 kB {0} [built]
 [113] ./src/index.js 827 bytes {0} [built]
 [114] ./src/css/main.scss 41 bytes {0} [built]
 [115] ./src/App.js 5.38 kB {0} [built]
 [119] ./src/views/About.js 4.18 kB {0} [built]
 [120] ./src/views/FAQ.js 11.5 kB {0} [built]
 [121] ./src/views/Pause.js 5.32 kB {0} [built]
 [122] ./src/views/Resume.js 13.3 kB {0} [built]
 [123] ./src/views/Start.js 21.4 kB {0} [built]
 [220] ./~/material-ui/Tabs/index.js 483 bytes {0} [built]
 [264] multi ./src/index.js ./src/css/main.scss 40 bytes {0} [built]
 [266] ./~/css-loader!./~/postcss-loader/src!./src/css/main.scss 5.29 kB [built]
 [268] ./~/style-loader/addStyles.js 6.91 kB [built]
    + 254 hidden modules
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
        + 1 hidden modules
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ./~/css-loader!./~/postcss-loader/src!./src/css/main.scss 5.29 kB {0} [built]

> google-drive-copy-folder@6.1.0 gulp:prod /Users/simonwoodside/sandbox/gdrive-copy
> gulp build

gulp[42701]: ../src/node_contextify.cc:649:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100ba09ba node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000846a1 node::FatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x100084459 node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 4: 0x10007b60b node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 5: 0x1001cb186 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 6: 0x1001ca53d v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 7: 0x1001c9ffc v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x100750119 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
 9: 0x1006d8301 Builtins_JSBuiltinsConstructStub [/usr/local/bin/node]
10: 0x1007bb11b Builtins_ConstructHandler [/usr/local/bin/node]
11: 0x1006dc1bb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
12: 0x1006dc1bb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
13: 0x1006dc1bb Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
sh: line 1: 42700 Abort trap: 6           npm run gulp:prod
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! google-drive-copy-folder@6.1.0 build:prod: `npm run webpack:prod && npm run gulp:prod && npm run copylib`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the google-drive-copy-folder@6.1.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simonwoodside/.npm/_logs/2020-01-14T03_46_55_693Z-debug.log

```

I don't know if the install `gyp` error is relevant but I did fix it separately and still got the same error in the build stage.

**Comment by ericyd** [comment]
Please use the node version listed in the readme
